// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckoutHandlerFunc turns a function with the right signature into a checkout handler
type CheckoutHandlerFunc func(CheckoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckoutHandlerFunc) Handle(params CheckoutParams) middleware.Responder {
	return fn(params)
}

// CheckoutHandler interface for that can handle valid checkout params
type CheckoutHandler interface {
	Handle(CheckoutParams) middleware.Responder
}

// NewCheckout creates a new http.Handler for the checkout operation
func NewCheckout(ctx *middleware.Context, handler CheckoutHandler) *Checkout {
	return &Checkout{Context: ctx, Handler: handler}
}

/*Checkout swagger:route POST /orders orders checkout

Create order for the cart

*/
type Checkout struct {
	Context *middleware.Context
	Handler CheckoutHandler
}

func (o *Checkout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckoutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
