// Code generated by go-swagger; DO NOT EDIT.

// Package restapi XenElectronic
//
//  e-Commerce application for XenElectronic
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/xenelectronic.v1+json
//
//  Produces:
//    - application/xenelectronic.v1+json
//
// swagger:meta
package restapi
