// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/xenelectronic.v1+json"
  ],
  "produces": [
    "application/xenelectronic.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "e-Commerce application for XenElectronic",
    "title": "XenElectronic",
    "version": "1.0.0"
  },
  "paths": {
    "/carts": {
      "post": {
        "description": "Create new cart",
        "tags": [
          "carts"
        ],
        "operationId": "createCart",
        "responses": {
          "200": {
            "description": "created new cart",
            "schema": {
              "type": "object",
              "required": [
                "cart_id"
              ],
              "properties": {
                "cart_id": {
                  "type": "string",
                  "format": "uuid"
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/carts/{cart_id}/products": {
      "get": {
        "description": "List Products in the cart",
        "tags": [
          "carts"
        ],
        "operationId": "listProductsInCart",
        "responses": {
          "200": {
            "description": "list the products in the cart",
            "schema": {
              "$ref": "#/definitions/CartItems"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Add a Product into cart",
        "tags": [
          "carts"
        ],
        "operationId": "addOneProductIntoCart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "product_id"
              ],
              "properties": {
                "product_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "add one product into the cart",
            "schema": {
              "$ref": "#/definitions/CartItem"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "format": "uuid",
          "name": "cart_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/carts/{cart_id}/products/{product_id}": {
      "delete": {
        "description": "Delete a Product from cart",
        "tags": [
          "carts"
        ],
        "operationId": "removeOneProductFromCart",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "name": "cart_id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "product_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "product is deleted from cart"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "description": "List available categories",
        "tags": [
          "categories"
        ],
        "operationId": "listCategories",
        "responses": {
          "200": {
            "description": "list the categories",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Category"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/categories/{category_id}/products": {
      "get": {
        "description": "List Products of a category",
        "tags": [
          "categories"
        ],
        "operationId": "listProductsOfCategory",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "category_id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the products of selected category",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Product"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/orders": {
      "post": {
        "description": "Create order for the cart",
        "tags": [
          "orders"
        ],
        "operationId": "checkout",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "cart_id",
                "customer_name",
                "customer_email",
                "customer_address"
              ],
              "properties": {
                "cart_id": {
                  "type": "string",
                  "format": "uuid"
                },
                "customer_address": {
                  "type": "string",
                  "minLength": 1
                },
                "customer_email": {
                  "type": "string",
                  "format": "email",
                  "minLength": 1
                },
                "customer_name": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created new order from cart",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CartItem": {
      "type": "object",
      "required": [
        "product_id"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "product": {
          "$ref": "#/definitions/Product",
          "readOnly": true
        },
        "product_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "CartItems": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CartItem"
      },
      "example": [
        {
          "id": 1000,
          "product": {
            "category_id": 1,
            "description": "Samsung LED TV",
            "id": 500,
            "name": "Samsung LED TV",
            "photo": "https://samsung.com",
            "price": 5000000
          },
          "product_id": 500
        },
        {
          "id": 1001,
          "product": {
            "category_id": 10,
            "description": "Samsung Galaxy S20 Ultra",
            "id": 550,
            "name": "Samsung Galaxy S20 Ultra",
            "photo": "https://samsung.com",
            "price": 20000000
          },
          "product_id": 550
        },
        {
          "id": 1002,
          "product": {
            "category_id": 0,
            "description": "iPhone 11 Pro",
            "id": 555,
            "name": "iPhone 11 Pro",
            "photo": "https://apple.com",
            "price": 20000000
          },
          "product_id": 555
        }
      ]
    },
    "Category": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Order": {
      "type": "object",
      "required": [
        "customer_name",
        "customer_email",
        "customer_address"
      ],
      "properties": {
        "cart_items": {
          "$ref": "#/definitions/CartItems"
        },
        "customer_address": {
          "type": "string",
          "minLength": 1
        },
        "customer_email": {
          "type": "string",
          "format": "email",
          "minLength": 1
        },
        "customer_name": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "payment_account_number": {
          "type": "string"
        },
        "payment_amount": {
          "type": "integer",
          "format": "int64"
        },
        "payment_method": {
          "type": "string"
        }
      },
      "example": {
        "cart_items": [
          {
            "id": 1000,
            "product": {
              "category_id": 1,
              "description": "Samsung LED TV",
              "id": 500,
              "name": "Samsung LED TV",
              "photo": "https://samsung.com",
              "price": 5000000
            },
            "product_id": 500
          },
          {
            "id": 1001,
            "product": {
              "category_id": 10,
              "description": "Samsung Galaxy S20 Ultra",
              "id": 550,
              "name": "Samsung Galaxy S20 Ultra",
              "photo": "https://samsung.com",
              "price": 20000000
            },
            "product_id": 550
          },
          {
            "id": 1002,
            "product": {
              "category_id": 0,
              "description": "iPhone 11 Pro",
              "id": 555,
              "name": "iPhone 11 Pro",
              "photo": "https://apple.com",
              "price": 20000000
            },
            "product_id": 555
          }
        ],
        "customer_address": "1 Hacker Way",
        "customer_email": "john@example.com",
        "customer_name": "John Doe",
        "id": "aaaaaaaa-bbbb-cccc-dddd-eeeedeadbeef",
        "payment_account_number": "232 555 8965",
        "payment_amount": 45000000,
        "payment_method": "Bank Transfer"
      }
    },
    "Product": {
      "type": "object",
      "required": [
        "name",
        "description",
        "price",
        "category_id"
      ],
      "properties": {
        "category_id": {
          "type": "integer",
          "format": "int64"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "photo": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/xenelectronic.v1+json"
  ],
  "produces": [
    "application/xenelectronic.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "e-Commerce application for XenElectronic",
    "title": "XenElectronic",
    "version": "1.0.0"
  },
  "paths": {
    "/carts": {
      "post": {
        "description": "Create new cart",
        "tags": [
          "carts"
        ],
        "operationId": "createCart",
        "responses": {
          "200": {
            "description": "created new cart",
            "schema": {
              "type": "object",
              "required": [
                "cart_id"
              ],
              "properties": {
                "cart_id": {
                  "type": "string",
                  "format": "uuid"
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/carts/{cart_id}/products": {
      "get": {
        "description": "List Products in the cart",
        "tags": [
          "carts"
        ],
        "operationId": "listProductsInCart",
        "responses": {
          "200": {
            "description": "list the products in the cart",
            "schema": {
              "$ref": "#/definitions/CartItems"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Add a Product into cart",
        "tags": [
          "carts"
        ],
        "operationId": "addOneProductIntoCart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "product_id"
              ],
              "properties": {
                "product_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "add one product into the cart",
            "schema": {
              "$ref": "#/definitions/CartItem"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "format": "uuid",
          "name": "cart_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/carts/{cart_id}/products/{product_id}": {
      "delete": {
        "description": "Delete a Product from cart",
        "tags": [
          "carts"
        ],
        "operationId": "removeOneProductFromCart",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "name": "cart_id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "product_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "product is deleted from cart"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "description": "List available categories",
        "tags": [
          "categories"
        ],
        "operationId": "listCategories",
        "responses": {
          "200": {
            "description": "list the categories",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Category"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/categories/{category_id}/products": {
      "get": {
        "description": "List Products of a category",
        "tags": [
          "categories"
        ],
        "operationId": "listProductsOfCategory",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "category_id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the products of selected category",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Product"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/orders": {
      "post": {
        "description": "Create order for the cart",
        "tags": [
          "orders"
        ],
        "operationId": "checkout",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "cart_id",
                "customer_name",
                "customer_email",
                "customer_address"
              ],
              "properties": {
                "cart_id": {
                  "type": "string",
                  "format": "uuid"
                },
                "customer_address": {
                  "type": "string",
                  "minLength": 1
                },
                "customer_email": {
                  "type": "string",
                  "format": "email",
                  "minLength": 1
                },
                "customer_name": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created new order from cart",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CartItem": {
      "type": "object",
      "required": [
        "product_id"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "product": {
          "$ref": "#/definitions/Product",
          "readOnly": true
        },
        "product_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "CartItems": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CartItem"
      },
      "example": [
        {
          "id": 1000,
          "product": {
            "category_id": 1,
            "description": "Samsung LED TV",
            "id": 500,
            "name": "Samsung LED TV",
            "photo": "https://samsung.com",
            "price": 5000000
          },
          "product_id": 500
        },
        {
          "id": 1001,
          "product": {
            "category_id": 10,
            "description": "Samsung Galaxy S20 Ultra",
            "id": 550,
            "name": "Samsung Galaxy S20 Ultra",
            "photo": "https://samsung.com",
            "price": 20000000
          },
          "product_id": 550
        },
        {
          "id": 1002,
          "product": {
            "category_id": 0,
            "description": "iPhone 11 Pro",
            "id": 555,
            "name": "iPhone 11 Pro",
            "photo": "https://apple.com",
            "price": 20000000
          },
          "product_id": 555
        }
      ]
    },
    "Category": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Order": {
      "type": "object",
      "required": [
        "customer_name",
        "customer_email",
        "customer_address"
      ],
      "properties": {
        "cart_items": {
          "$ref": "#/definitions/CartItems"
        },
        "customer_address": {
          "type": "string",
          "minLength": 1
        },
        "customer_email": {
          "type": "string",
          "format": "email",
          "minLength": 1
        },
        "customer_name": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "payment_account_number": {
          "type": "string"
        },
        "payment_amount": {
          "type": "integer",
          "format": "int64"
        },
        "payment_method": {
          "type": "string"
        }
      },
      "example": {
        "cart_items": [
          {
            "id": 1000,
            "product": {
              "category_id": 1,
              "description": "Samsung LED TV",
              "id": 500,
              "name": "Samsung LED TV",
              "photo": "https://samsung.com",
              "price": 5000000
            },
            "product_id": 500
          },
          {
            "id": 1001,
            "product": {
              "category_id": 10,
              "description": "Samsung Galaxy S20 Ultra",
              "id": 550,
              "name": "Samsung Galaxy S20 Ultra",
              "photo": "https://samsung.com",
              "price": 20000000
            },
            "product_id": 550
          },
          {
            "id": 1002,
            "product": {
              "category_id": 0,
              "description": "iPhone 11 Pro",
              "id": 555,
              "name": "iPhone 11 Pro",
              "photo": "https://apple.com",
              "price": 20000000
            },
            "product_id": 555
          }
        ],
        "customer_address": "1 Hacker Way",
        "customer_email": "john@example.com",
        "customer_name": "John Doe",
        "id": "aaaaaaaa-bbbb-cccc-dddd-eeeedeadbeef",
        "payment_account_number": "232 555 8965",
        "payment_amount": 45000000,
        "payment_method": "Bank Transfer"
      }
    },
    "Product": {
      "type": "object",
      "required": [
        "name",
        "description",
        "price",
        "category_id"
      ],
      "properties": {
        "category_id": {
          "type": "integer",
          "format": "int64"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "photo": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
}
