// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gifff/xenelectronic/models"
)

// ListCategoriesOKCode is the HTTP code returned for type ListCategoriesOK
const ListCategoriesOKCode int = 200

/*ListCategoriesOK list the categories

swagger:response listCategoriesOK
*/
type ListCategoriesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Category `json:"body,omitempty"`
}

// NewListCategoriesOK creates ListCategoriesOK with default headers values
func NewListCategoriesOK() *ListCategoriesOK {

	return &ListCategoriesOK{}
}

// WithPayload adds the payload to the list categories o k response
func (o *ListCategoriesOK) WithPayload(payload []*models.Category) *ListCategoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list categories o k response
func (o *ListCategoriesOK) SetPayload(payload []*models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Category, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListCategoriesDefault generic error response

swagger:response listCategoriesDefault
*/
type ListCategoriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListCategoriesDefault creates ListCategoriesDefault with default headers values
func NewListCategoriesDefault(code int) *ListCategoriesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListCategoriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list categories default response
func (o *ListCategoriesDefault) WithStatusCode(code int) *ListCategoriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list categories default response
func (o *ListCategoriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list categories default response
func (o *ListCategoriesDefault) WithPayload(payload *models.Error) *ListCategoriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list categories default response
func (o *ListCategoriesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListCategoriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
