// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListCategoriesHandlerFunc turns a function with the right signature into a list categories handler
type ListCategoriesHandlerFunc func(ListCategoriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListCategoriesHandlerFunc) Handle(params ListCategoriesParams) middleware.Responder {
	return fn(params)
}

// ListCategoriesHandler interface for that can handle valid list categories params
type ListCategoriesHandler interface {
	Handle(ListCategoriesParams) middleware.Responder
}

// NewListCategories creates a new http.Handler for the list categories operation
func NewListCategories(ctx *middleware.Context, handler ListCategoriesHandler) *ListCategories {
	return &ListCategories{Context: ctx, Handler: handler}
}

/*ListCategories swagger:route GET /categories categories listCategories

List available categories

*/
type ListCategories struct {
	Context *middleware.Context
	Handler ListCategoriesHandler
}

func (o *ListCategories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListCategoriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
