// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gifff/xenelectronic/models"
)

// ListProductsOfCategoryOKCode is the HTTP code returned for type ListProductsOfCategoryOK
const ListProductsOfCategoryOKCode int = 200

/*ListProductsOfCategoryOK list the products of selected category

swagger:response listProductsOfCategoryOK
*/
type ListProductsOfCategoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Product `json:"body,omitempty"`
}

// NewListProductsOfCategoryOK creates ListProductsOfCategoryOK with default headers values
func NewListProductsOfCategoryOK() *ListProductsOfCategoryOK {

	return &ListProductsOfCategoryOK{}
}

// WithPayload adds the payload to the list products of category o k response
func (o *ListProductsOfCategoryOK) WithPayload(payload []*models.Product) *ListProductsOfCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products of category o k response
func (o *ListProductsOfCategoryOK) SetPayload(payload []*models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsOfCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Product, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListProductsOfCategoryDefault generic error response

swagger:response listProductsOfCategoryDefault
*/
type ListProductsOfCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListProductsOfCategoryDefault creates ListProductsOfCategoryDefault with default headers values
func NewListProductsOfCategoryDefault(code int) *ListProductsOfCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &ListProductsOfCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list products of category default response
func (o *ListProductsOfCategoryDefault) WithStatusCode(code int) *ListProductsOfCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list products of category default response
func (o *ListProductsOfCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list products of category default response
func (o *ListProductsOfCategoryDefault) WithPayload(payload *models.Error) *ListProductsOfCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products of category default response
func (o *ListProductsOfCategoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsOfCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
