// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import (
	entity "github.com/gifff/xenelectronic/entity"
	mock "github.com/stretchr/testify/mock"
)

// CartRepository is an autogenerated mock type for the CartRepository type
type CartRepository struct {
	mock.Mock
}

// AddProductIntoCart provides a mock function with given fields: cartID, productID
func (_m *CartRepository) AddProductIntoCart(cartID string, productID int64) (entity.CartItem, error) {
	ret := _m.Called(cartID, productID)

	var r0 entity.CartItem
	if rf, ok := ret.Get(0).(func(string, int64) entity.CartItem); ok {
		r0 = rf(cartID, productID)
	} else {
		r0 = ret.Get(0).(entity.CartItem)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(cartID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCart provides a mock function with given fields:
func (_m *CartRepository) CreateCart() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProductsByCartID provides a mock function with given fields: cartID
func (_m *CartRepository) ListProductsByCartID(cartID string) ([]entity.CartItem, error) {
	ret := _m.Called(cartID)

	var r0 []entity.CartItem
	if rf, ok := ret.Get(0).(func(string) []entity.CartItem); ok {
		r0 = rf(cartID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CartItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cartID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveProductFromCart provides a mock function with given fields: cartID, productID
func (_m *CartRepository) RemoveProductFromCart(cartID string, productID int64) error {
	ret := _m.Called(cartID, productID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(cartID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
