// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import (
	entity "github.com/gifff/xenelectronic/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CheckoutFromCart provides a mock function with given fields: cartID, customerName, customerEmail, customerAddress
func (_m *OrderRepository) CheckoutFromCart(cartID string, customerName string, customerEmail string, customerAddress string) (entity.Order, error) {
	ret := _m.Called(cartID, customerName, customerEmail, customerAddress)

	var r0 entity.Order
	if rf, ok := ret.Get(0).(func(string, string, string, string) entity.Order); ok {
		r0 = rf(cartID, customerName, customerEmail, customerAddress)
	} else {
		r0 = ret.Get(0).(entity.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(cartID, customerName, customerEmail, customerAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
