// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewAddOneProductIntoCartParams creates a new AddOneProductIntoCartParams object
// no default values defined in spec.
func NewAddOneProductIntoCartParams() AddOneProductIntoCartParams {

	return AddOneProductIntoCartParams{}
}

// AddOneProductIntoCartParams contains all the bound params for the add one product into cart operation
// typically these are obtained from a http.Request
//
// swagger:parameters addOneProductIntoCart
type AddOneProductIntoCartParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body AddOneProductIntoCartBody
	/*
	  Required: true
	  In: path
	*/
	CartID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddOneProductIntoCartParams() beforehand.
func (o *AddOneProductIntoCartParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body AddOneProductIntoCartBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	rCartID, rhkCartID, _ := route.Params.GetOK("cart_id")
	if err := o.bindCartID(rCartID, rhkCartID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCartID binds and validates parameter CartID from path.
func (o *AddOneProductIntoCartParams) bindCartID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("cart_id", "path", "strfmt.UUID", raw)
	}
	o.CartID = *(value.(*strfmt.UUID))

	if err := o.validateCartID(formats); err != nil {
		return err
	}

	return nil
}

// validateCartID carries on validations for parameter CartID
func (o *AddOneProductIntoCartParams) validateCartID(formats strfmt.Registry) error {

	if err := validate.FormatOf("cart_id", "path", "uuid", o.CartID.String(), formats); err != nil {
		return err
	}
	return nil
}
