// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gifff/xenelectronic/models"
)

// CreateCartOKCode is the HTTP code returned for type CreateCartOK
const CreateCartOKCode int = 200

/*CreateCartOK created new cart

swagger:response createCartOK
*/
type CreateCartOK struct {

	/*
	  In: Body
	*/
	Payload *CreateCartOKBody `json:"body,omitempty"`
}

// NewCreateCartOK creates CreateCartOK with default headers values
func NewCreateCartOK() *CreateCartOK {

	return &CreateCartOK{}
}

// WithPayload adds the payload to the create cart o k response
func (o *CreateCartOK) WithPayload(payload *CreateCartOKBody) *CreateCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cart o k response
func (o *CreateCartOK) SetPayload(payload *CreateCartOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateCartDefault generic error response

swagger:response createCartDefault
*/
type CreateCartDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCartDefault creates CreateCartDefault with default headers values
func NewCreateCartDefault(code int) *CreateCartDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateCartDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create cart default response
func (o *CreateCartDefault) WithStatusCode(code int) *CreateCartDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create cart default response
func (o *CreateCartDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create cart default response
func (o *CreateCartDefault) WithPayload(payload *models.Error) *CreateCartDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cart default response
func (o *CreateCartDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCartDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
