// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewListProductsInCartParams creates a new ListProductsInCartParams object
// no default values defined in spec.
func NewListProductsInCartParams() ListProductsInCartParams {

	return ListProductsInCartParams{}
}

// ListProductsInCartParams contains all the bound params for the list products in cart operation
// typically these are obtained from a http.Request
//
// swagger:parameters listProductsInCart
type ListProductsInCartParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	CartID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListProductsInCartParams() beforehand.
func (o *ListProductsInCartParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCartID, rhkCartID, _ := route.Params.GetOK("cart_id")
	if err := o.bindCartID(rCartID, rhkCartID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCartID binds and validates parameter CartID from path.
func (o *ListProductsInCartParams) bindCartID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("cart_id", "path", "strfmt.UUID", raw)
	}
	o.CartID = *(value.(*strfmt.UUID))

	if err := o.validateCartID(formats); err != nil {
		return err
	}

	return nil
}

// validateCartID carries on validations for parameter CartID
func (o *ListProductsInCartParams) validateCartID(formats strfmt.Registry) error {

	if err := validate.FormatOf("cart_id", "path", "uuid", o.CartID.String(), formats); err != nil {
		return err
	}
	return nil
}
