// Code generated by go-swagger; DO NOT EDIT.

package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gifff/xenelectronic/models"
)

// ListProductsInCartOKCode is the HTTP code returned for type ListProductsInCartOK
const ListProductsInCartOKCode int = 200

/*ListProductsInCartOK list the products in the cart

swagger:response listProductsInCartOK
*/
type ListProductsInCartOK struct {

	/*
	  In: Body
	*/
	Payload models.CartItems `json:"body,omitempty"`
}

// NewListProductsInCartOK creates ListProductsInCartOK with default headers values
func NewListProductsInCartOK() *ListProductsInCartOK {

	return &ListProductsInCartOK{}
}

// WithPayload adds the payload to the list products in cart o k response
func (o *ListProductsInCartOK) WithPayload(payload models.CartItems) *ListProductsInCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products in cart o k response
func (o *ListProductsInCartOK) SetPayload(payload models.CartItems) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsInCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.CartItems{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListProductsInCartDefault generic error response

swagger:response listProductsInCartDefault
*/
type ListProductsInCartDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListProductsInCartDefault creates ListProductsInCartDefault with default headers values
func NewListProductsInCartDefault(code int) *ListProductsInCartDefault {
	if code <= 0 {
		code = 500
	}

	return &ListProductsInCartDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list products in cart default response
func (o *ListProductsInCartDefault) WithStatusCode(code int) *ListProductsInCartDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list products in cart default response
func (o *ListProductsInCartDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list products in cart default response
func (o *ListProductsInCartDefault) WithPayload(payload *models.Error) *ListProductsInCartDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products in cart default response
func (o *ListProductsInCartDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsInCartDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
