// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExtendedOrder extended order
//
// swagger:model ExtendedOrder
type ExtendedOrder struct {
	Order

	// cart items
	CartItems CartItems `json:"cart_items,omitempty"`

	// payment account number
	PaymentAccountNumber string `json:"payment_account_number,omitempty"`

	// payment amount
	PaymentAmount int64 `json:"payment_amount,omitempty"`

	// payment method
	PaymentMethod string `json:"payment_method,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExtendedOrder) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Order
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Order = aO0

	// AO1
	var dataAO1 struct {
		CartItems CartItems `json:"cart_items,omitempty"`

		PaymentAccountNumber string `json:"payment_account_number,omitempty"`

		PaymentAmount int64 `json:"payment_amount,omitempty"`

		PaymentMethod string `json:"payment_method,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.CartItems = dataAO1.CartItems

	m.PaymentAccountNumber = dataAO1.PaymentAccountNumber

	m.PaymentAmount = dataAO1.PaymentAmount

	m.PaymentMethod = dataAO1.PaymentMethod

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExtendedOrder) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Order)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		CartItems CartItems `json:"cart_items,omitempty"`

		PaymentAccountNumber string `json:"payment_account_number,omitempty"`

		PaymentAmount int64 `json:"payment_amount,omitempty"`

		PaymentMethod string `json:"payment_method,omitempty"`
	}

	dataAO1.CartItems = m.CartItems

	dataAO1.PaymentAccountNumber = m.PaymentAccountNumber

	dataAO1.PaymentAmount = m.PaymentAmount

	dataAO1.PaymentMethod = m.PaymentMethod

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this extended order
func (m *ExtendedOrder) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Order
	if err := m.Order.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCartItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtendedOrder) validateCartItems(formats strfmt.Registry) error {

	if swag.IsZero(m.CartItems) { // not required
		return nil
	}

	if err := m.CartItems.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("cart_items")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExtendedOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtendedOrder) UnmarshalBinary(b []byte) error {
	var res ExtendedOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
